(defun C:LINTERNA()
  (command "_OSMODE" 0)
  (command "_SURFTAB1" 20)
  (command "_SURFTAB2" 20)
  (command "_ISOLINES" 20)
  ;
  (setq base (getpoint "Base linterna:"))  
  (command "_CYLINDER" base 20 20)
  (setq base (entlast))
  (setq p1 (list (+ 20 (nth 0 pBase)) (nth 1 pBase) (nth 2 pBase) ))
  (command "cylinder" p1 3 20)
  (setq aux1(entlast))
  (command "arraypolar" aux1 "" pBase "i" 15 "" "exit" "")
  (setq aux2(entlast))
  (command "explode" aux2)  
  (setq aux3(ssget "p"))
  (command "subtract" base "" aux3 "" "")
  ;
  (setq p2 (list (nth 0 pBase) (nth 1 pBase) (+ (nth 2 pBase) 20) ))
  (command "sphere" p2 20)
  (setq esfera1(entlast))
  (command "cylinder" pBase 20 20)
  (setq aux1(entlast))
  (command "subtract" esfera1 "" aux1 "" "")
  (command "cylinder" p2 10 60)
  (setq aux1(entlast))
  (command "union" esfera1 aux1 "")
  ;
  (setq p3 (list (nth 0 pBase) (nth 1 pBase)  (+ (nth 2 pBase) 80) ))
  (command "sphere" p3 10)
  (setq esfera2(entlast))
  (command "cylinder" p2 10 60)
  (setq aux1(entlast))
  (command "subtract" esfera2 "" aux1 "" "")
  (command "cylinder" p3 2 18)
  (setq aux2(entlast))
  ;
  (setq p4 (list (nth 0 pBase) (nth 1 pBase)  (+ (nth 2 pBase) 98) ))
  (command "sphere" p4 2)
  (setq esfera3(entlast))
  (command "union" esfera3 aux2 esfera2 "")
  ;
  (setq p5 (list (nth 0 p3) (- (nth 1 p3) 2 ) (- (nth 2 p3) 2 ) ))
  (setq p6 (list (+ 15 (nth 0 p5)) (+ (nth 1 p5)4)(- (nth 2 p5) 2 ) ))
  (command "box" p5 p6)
  (setq enganche1(entlast))
  ;
  (setq p7 (list (- (nth 0 p6) 2 ) (- (nth 1 p6) 4) (- (nth 2 p6 )20) ))
  (command "box" p6 p7)
  (setq enganche2(entlast))
  ;
  (command "union" enganche1 enganche2 "")
)